@startuml user_authentication_state
state "AccountAuthStateProvider" as Authentication {
    state "Unauthenticated" as Unauthenticated
    state "Authenticated" as Authenticated

    [*] --> Unauthenticated
    Unauthenticated --> Authenticated  : MarkUserAsAuthenticatedAsync()
    Authenticated -right-> Unauthenticated : MarkUserAsLoggedOut()
}
@enduml
