@startuml
node "Client Browser" as Client <<device>> {
  node "WASM Dotnet runtime" as ClientRuntime <<execution environment>> {
        artifact "Client.dll" <<executable>>
    }
}

node "Azure Server" as Server <<device>> { 
    node "Linux" as Linux <<execution environment>> {
        node "Dotnet Runtime" as Dotnet <<execution environment>> {
            artifact "Server.dll" as ServerArtifact <<executable>>
        }
        artifact "SQLiteDB" as SQLiteDB <<file>>
    }
}

' Communication between nodes
Client --> Server : HTTPS
@enduml
