@startuml united_package_diagram
'!pragma layout smetana

    package "Client" {
        package "Components" {}
        package "Pages" {}
        package "Services" {}

        
    }

    package "Server" {
        package "Controllers" {}
        package "Services" {}
        package "Enums" {}
        package "Repositories" {}
        package "Database" {}
    }



    package "Shared" {
        package "Enums" {}
        package "Models" {}
    }

    'lient.Pages -- Server.Controllers


    Client.Pages "<<Import>>"..> Client.Components
    Client.Pages "<<Import>>"..> Client.Services



    Server.Controllers "<<Import>>"..> Server.Services
  

    Server.Services "<<Import>>"..> Server.Repositories
    Server.Services "<<Import>>"..> Server.Enums

    Server.Repositories "<<Import>>"..> Server.Database

    Shared.Models <.."<<Import>>" Client.Pages
    Shared.Models <.."<<Import>>" Server.Controllers

    Shared.Enums <.."<<Import>>" Client.Pages
    Shared.Enums <.."<<Import>>" Client.Services

    Shared.Enums <.."<<Import>>" Server.Controllers
    Shared.Enums <.."<<Import>>" Server.Services



@enduml
