@startuml use_case_game_page
left to right direction
:Player: as player

rectangle "Game Page" as game_page {
   usecase "Start game" as start_game
   usecase "Change difficulty" as change_difficulty
}

player --> start_game
player --> change_difficulty
@enduml
