@startuml use_case_high_score
left to right direction
:Player: as player

rectangle "Statistics" as hs_module {
    usecase "Change high score visibility" as view_by_difficulty
    usecase "View shortened game statistics" as view_shortened
    usecase "View graph of average scores" as view_graph
    usecase "View timeline of played games" as view_timeline
}

player --> view_shortened
player --> view_graph
player --> view_timeline
player --> view_by_difficulty
@enduml
